LEARNING_RATE : 1e-4
LEARNING_SCHEDULER : CosineAnnealingLR
DECAY_STEP : 5
OPTIMIZER : 0 #0: AdamW, 1: SAM
BATCH_SIZE : 32
NUM_EPOCHS : 30
FINETUNE: True
FINETUNE_EPOCHS : 20
FINETUNE_LR : 1e-5
EARLY_STOPPING : False
PATIENCE : 50

WARMUP_EPOCHS : 10
WARMUP_LR : 1e-5

IMAGE_SIZE : 224

MODEL: TransConvNeXtV2Base
PRETRAINED: True
FREEZE: True
UNFREEZE_LAYERS : True
LOSS: CrossEntropyLoss

DATASET: 0 # 0: CUB, 1: FGVC-Aircraft, 2: FoodX, 3:Concated
CONCAT_DATASET: False

LABEL_SMOOTHING: 0.1