LEARNING_RATE : 3e-4
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 128
NUM_EPOCHS : 200
LINEAR_PROBING: True
PROBING_EPOCHS : 50
PATIENCE : 50

IMAGE_SIZE : 256

MODEL: DenseNet121
PRETRAINED: True
LOSS: CrossEntropyLoss